### ISSUE TITLE
Correct handling of tracker type "standard fields"

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt_smash#15]
**Problem**
The plugin API point currently returns all default tracker "Standard fields", even if they are not enabled in `/trackers` configuration, because their checkbox is unchecked.

**To Reproduce**
Create a "minimal" tracker by unchecking all not required fields.

**Expectation**
Only return the following Standard Fields attributes if enabled:
- Assignee
- Category
- Target version
- Parent task
- Start date
- Due date
- Estimated time
- % Done
- Description 

To be confirmed, but this would mean the following minimum attributes:
- project
- tracker
- status
- priority
- subject

Other standard fields may be disabled for a tracker type.

**Comment by sanak** [comment]
@dkastl (CC: @mbasa)
Well, about Standard fields, `Assignee` and `Parent task` may become quite difficult, because those require another `User` and `Issue` model which can be specified by the user.

Other fields should be okay, although more `Category` and `Version` list fetch implementation is necessary.

**Comment by dkastl** [comment]
Well, I just took the list of checkboxes and didn't really think about whether they make sense to be part of the form in SMASH.
Assignee and Parent task for example won't work properly, so let's decide which standard fields we want to include into a SMASH form, but if they are disabled on Redmine side, then they also should be disabled on the SMASH form.

I would say the following fields make sense to appear in the mobile device (and need to disappear when unchecked in the tracker settings):
- Estimated time
- Description

Not sure if this is easy, but it could be useful:
- Category

Not sure about these ... maybe annoying for users? Or useful?
- Start date
- Due date

So in the end there are just `estimated time` and `description` that should not be in the form, if disabled in the tracker settings.

**Comment by sanak** [comment]
@dkastl Well, Redmine default is all, so controlling it by Redmine Tracker UI may be better.

By the way, `Category` and `Target version` will be difficult in case of #17 (global tags.json settings), because those are belong to a project.

**Comment by dkastl** [comment]
That's true with Category. Shall we assume that relevant standard fields are not disabled?

**Comment by sanak** [comment]
Well, supporting disable standard fields itself is not so difficult, so just defining unavailable standard fields (like `Assignee` and `Parent task`) should be enough.

**Comment by dkastl** [comment]
OK, this sounds good. Also standard fields are likely not going to change in 100 years (looking at Redmine governance ;-) ).
So having hardcoded which standard fields are part of the SMASH form is fine. We just want to make sure, that we do not include disabled fields.
