### ISSUE TITLE
tags.json for whole Redmine instance

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt_smash#17]
To support multiple projects at once, let's add another API endpoint, for example `/smash_tags.json` on the root level.

Expected functionality
- [x] returns all tracker types
- [x] makes the `project_id` field public
- [x] makes the `project_id` field a select field with all available projects as option.
- [x] takes into account that the SMASH module is enabled
- [x] takes into account role permissions if possible
- [x] takes into account #16 and #15

**Comment by sanak** [comment]
As I mentioned in https://github.com/gtt-project/redmine_gtt_smash/issues/15#issuecomment-797176641, supporting `Category` and `Target version` will be impossible in this endpoint.

**Comment by dkastl** [comment]
Yes, that's fine. So it will never be part of the SMASH form but only supported on the desktop.

**Comment by sanak** [comment]
Okay.

About the following,
> takes into account role permissions if possible

there seems to be convenient function (`Tracker.visible(user)`).
https://github.com/redmica/redmica/blob/master/app/models/tracker.rb#L50-L71

**Comment by sanak** [comment]
I missed the following, so above `Tracker.visible(user)` can't be used as it is...
> takes into account that the SMASH module is enabled
