### ISSUE TITLE
Set "GTT" as "sectiondescription" value in "tags.json"

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt_smash#22]
**Problem**
Currently, SMASH app side can't detect which section comes from GTT, so exporting time, this becomes problem.

**Improvement**
Set `GTT` as `sectiondescription` value in `tags.json`.

**Comment by dkastl** [comment]
I think my first thought was, that a note needs to have at least `project_id` in the form, whether hidden with preset value or selected. So looping through all notes during export, just all invalid notes not having `project_id` would be skipped.

The extra identifier makes this maybe a bit easier, but isn't a guarantee as still something could go wrong later.

**Comment by sanak** [comment]
@dkastl (CC: @mbasa-georepublic)
Well, checking child items may take a certain time.  
Other possibility is defining `sectiontype` = `GTT` as you mentioned, but it may requires `smashlibs` side modification.

**Comment by dkastl** [comment]
Well, I'm fine with some conventions in `sectiondescription`, if they cannot be accidentially changed by users.

**Comment by sanak** [comment]
@dkastl  
Okay, thanks.  
I just made the Pull Request #23, so could you approve that ?

**Comment by dkastl** [comment]
> Well, checking child items may take a certain time.

As far as I understand each recorded note item has exactly one form with content.
I still don't see how this
```
IF note > sectiondescription CONTAINS "GTT"
    CREATE ISSUE
    ....
ELSE
    IGNORE
```
is easier to check than
```
IF note > forms[0] > formitems HAS {key: project_id}
    CREATE ISSUE
   ....
ELSE
    IGNORE
```
