### ISSUE TITLE
Include "id" in custom form tags.json as hidden field

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt_smash#28]
Adding the ID field, which would be empty at first but could then be filled with the returned issue ID after creation on Redmine.
So from that moment it's clear if the issue is new or exists already.
Actually some timestamps could be also useful as hidden field.

https://www.geopaparazzi.org/geopaparazzi/index.html#_other_supported_tags

**Comment by sanak** [comment]
Implemented at client side. Close this.
