### ISSUE TITLE
SMASH android app configuration

### ISSUE THREAD

**Issue by jmtemmos** [gtt-project/redmine_gtt_smash#33]
Hi. Thanks for your great gtt plugin.

I probably miss something here: is a GSS server required or does this redmine plugin provides direct connection with the smash app ?

Trying to configure the SMASH Android app, there is only a server url and a password for the GSS export.

I do not see the fields for the global / project API  endpoints you provide.

Thanks by advance

Regards

**Comment by dkastl** [comment]
This plugin is for Redmine to be able to create notes with SMASH and turn them into Redmine issues. 

SMASH originally allows to interact with GSS, and the way we added Redmine support is similar. That said, right now SMASH needs to be compiled because the functionality is not yet available in the version available in the app stores. 
https://github.com/hyakumori/smash

Interest by the community definitely makes it easier to add this functionality to upstream SMASH.

**Comment by jmtemmos** [comment]
Thanks a lot for your answer.
OK, downloaded source code and trying to compile with android-studio on linux (new to flutter....):
Error in redmine-gtt/SMASH/smash-version_1.6.5-56_gtt/.dart_tool/package_config.json does not exist.
In case you have a repo of build  apk, it would be great.....
Otherwise, still trying to make it compile.

Congrats for your great job !

Best regards.

**Comment by dkastl** [comment]
Ah, I see. I thought Github Actions would be enabled eventually to build apk.

This is a bit early stage still, and we are still trying to get localization completed, so at the moment this requires a bit of research and trial/error. Sorry for that. The final goal would be to have this GTT functionality available in the offical release of the app store. But this may still take some time and coordination.

@sanak , do you have some more recent Android build of the GTT SMASH version. Is there something to care about when building the APK? Maybe we could enable Github Actions and run automatic builds and store them as artifacts.

**Comment by jmtemmos** [comment]
Thanks a lot.
This would be fantastic to have the apk and be able to start testing it.
Regards

**Comment by semanticts** [comment]
Hello. Thanks @sanak (and @dkastl of course) for the Android package.
Can go a bit further now. Running docker-gtt and configuring it ok. Installed Android gtt-patched app on my smartphone.
But after following the guide to setup the redmine server, still not clear how to upload notes frrom smash to a given project.
I guess Export should do it but still missing something.

I have huge interest in this project and would like to make at least a simple note upload / download to/from a redmine project work....

Thanks a lot

**Comment by dkastl** [comment]
Have you tried "Simple Notes"? Because this will not work right now as Redmine tracker types usually require more fields than "Simple Notes" collect.

**Comment by jmtemmos** [comment]
Right :)

Indeed.....Ok ... so Form Notes working fine.

Seems logical now :)

What about GPS logs ?
Any roadmap ?

Thanks for this great project !



Le lun. 17 janv. 2022 à 15:45, Daniel Kastl ***@***.***> a
écrit :

**Comment by dkastl** [comment]
The idea (or you call it roadmap exists), see:

- https://github.com/hyakumori/smash/issues/38
- https://github.com/hyakumori/smash/issues/34

But this needs a solution/idea for the problem of required fields of tracker types, which could be even further customized with custom fields. I think this could be done with some settings and checks on the Redmine plugin side. If you have some idea, feel free to share it in the issues.
