### ISSUE TITLE
Document workflow for processing Simple Forms 

### ISSUE THREAD

**Issue by mbasa-geolonia** [gtt-project/redmine_gtt_smash#36]
To process Simple Notes, Simple Photos, GPS Log can be documented as:

### Redmine Administraion
* create a Tracker named `Field Reports` in whatever language (Japanese, German, Italian) the administrator finds appropriate. 
* ensure that no Custom Fields are created for this Issue.
* move this Tracker at the very top of the list of Trackers.

### In the Field
* in SMASH, create a Simple Note, Simple Photo, or GPS Log.
* when Internet is available, do an export to GTT.

###  In the Office
* access and edit the created Issues to add more information concerning the Issue.
* change the **Tracker** into whatever the User deems correct.

**Comment by dkastl** [comment]
> change the Tracker into whatever the User deems correct.

Thought about this quickly yesterday, and is my assumption right, that from the moment a tracker type is changed, further editing would not work? .... or just eventually would not work anymore?

**Comment by sanak** [comment]
In my understanding, this has been already done, so I close this.
