### ISSUE TITLE
Empty project is possible on form note

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt_smash#47]
**Problem**
Currently, empty project is possible on form note, but it will be never uploaded from GTT export.

**To Reproduce**
Keep project selection to empty in form note.

**Expectation**
Project field should be mandatory.

**Screenshots**
<img src="https://user-images.githubusercontent.com/629923/174725339-db17794e-2505-492b-a677-94391a9a6f08.jpg" width="300px">

**Comment by nobnisai** [comment]
I guess we should put it this way (not mandatory) since the user will edit it later and can only upload it unless there is a project selected.

**Comment by dkastl** [comment]
Well, for "form notes" this should be mandatory and this should be configured by the Redmine plugin. There is not a single project possible for all tracker types.

**Comment by nobnisai** [comment]
Actually, the user won't be able to upload the notes anyway unless they assigned the project for that notes. So I think it's not necessary to set it to mandatory while we have the edit button for the user to edit it later whenever they want to assign the project.

**Comment by sanak** [comment]
Well, other data except form note can be configured at one place (on GTT export 1st screen) at one time, but form note needs to be set in all form notes.

So, I think that it's better to set mandatory to the project field, because this is the main functionality of this redmine_gtt_smash plugin.

**Comment by sanak** [comment]
@nobnisai, @dkastl  
Can I take this part and create PR ?

**Comment by sanak** [comment]
Well, I set `mandatory: "yes"` already,
https://github.com/gtt-project/redmine_gtt_smash/blob/main/app/controllers/smash_tags_controller.rb#L150-L157

so I think the cause is that smashlibs side `StringCombo` widget doesn't have mandatory constraints as validator.
https://github.com/geopaparazzi/smashlibs/blob/master/lib/com/hydrologis/flutterlibs/ui/ui.dart#L447-L489

I will create a new issue for this on upstream smashlibs side, later.

**Comment by sanak** [comment]
I created the following issue, so I close this issue.
https://github.com/geopaparazzi/smashlibs/issues/6
